### ISSUE TITLE
using pathogen on Vim 7.0 hangs, export VIMBLACKLIST=Y is required

### ISSUE THREAD

**Issue by LeoGalleguillos** [tpope/vim-pathogen#166] opened 2015-11-27 17:58 UTC
Using pathogen with Vim 7.0 hangs for me. The solution, as mentioned in a previous thread, was:

export VIMBLACKLIST=Y
vim

I'm on CentOS 5, so Vim 7.0 is the latest version of Vim natively available for now. We'll upgrade to CenOS 6 or 7 sometime during 2016.

Any chance we could get a patch for this in the meantime?

**Comment by tpope** [comment] 2016-01-20 01:15
Dupe of #136

**Closed** 2016-01-20 01:15 UTC
